/**
 * Единый источник правды для реестра модулей — app/modules_registry.json
 * на бэкенде (см. app/api/modules.py и README.md бэкенда). Этот файл его
 * зеркалит вручную, как и было условлено при закрытии Этапа 1 ("когда
 * появится фронтенд, modules.config.ts может либо импортировать этот JSON,
 * либо просто зеркалить его вручную — источник правды один"). Если оба
 * файла разойдутся, `GET /api/modules` на бэкенде — правильный.
 */
export interface ModuleConfig {
  key: string;
  section: "telegram_tools" | "content" | "utility" | "design" | "growth";
  order: number;
  title: string;
  description: string;
  icon: string;
  route: string;
  backendEndpoint: string | null;
  savesToHistory: boolean;
}

export const modulesConfig: ModuleConfig[] = [
  {
    key: "username_checker",
    section: "telegram_tools",
    order: 1,
    title: "Username Checker",
    description: "Проверка, свободен ли username для канала или бота",
    icon: "at-sign",
    route: "/tools/username-checker",
    backendEndpoint: "GET /api/tools/username-checker",
    savesToHistory: false,
  },
  {
    key: "bio_generator",
    section: "telegram_tools",
    order: 2,
    title: "Bio Generator",
    description: "Быстрая генерация короткого био для канала, бота или профиля",
    icon: "sparkles",
    route: "/tools/bio-generator",
    backendEndpoint: "POST /api/tools/bio-generator",
    savesToHistory: true,
  },
  {
    key: "deep_link_builder",
    section: "telegram_tools",
    order: 3,
    title: "Deep Link Builder",
    description: "Сборка deep-link ссылки на бота + QR-код",
    icon: "link",
    route: "/tools/deep-link-builder",
    backendEndpoint: "POST /api/tools/deep-link-builder",
    savesToHistory: true,
  },
  {
    key: "markdown_builder",
    section: "telegram_tools",
    order: 4,
    title: "Markdown Builder",
    description: "Разметка с живым превью и экспортом в Markdown / MarkdownV2 / HTML",
    icon: "text-cursor",
    route: "/tools/markdown-builder",
    backendEndpoint: null,
    savesToHistory: true,
  },
  {
    key: "unicode_fonts",
    section: "telegram_tools",
    order: 5,
    title: "Unicode Fonts",
    description: "Стилизованный unicode-текст и невидимые символы",
    icon: "type",
    route: "/tools/unicode-fonts",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "text_cleaner",
    section: "telegram_tools",
    order: 6,
    title: "Text Cleaner",
    description: "Очистка текста перед публикацией: пробелы, кавычки, эмодзи, HTML",
    icon: "eraser",
    route: "/tools/text-cleaner",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "password_generator",
    section: "utility",
    order: 1,
    title: "Password Generator",
    description: "Генератор паролей с индикатором силы — ничего не сохраняется",
    icon: "key-round",
    route: "/tools/password-generator",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "json_formatter",
    section: "utility",
    order: 2,
    title: "JSON Formatter",
    description: "Форматирование, минификация и сортировка ключей JSON с подсветкой ошибок",
    icon: "braces",
    route: "/tools/json-formatter",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "base64_tool",
    section: "utility",
    order: 3,
    title: "Base64 Encoder/Decoder",
    description: "Кодирование и декодирование Base64 с поддержкой кириллицы и emoji",
    icon: "binary",
    route: "/tools/base64",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "timestamp_converter",
    section: "utility",
    order: 4,
    title: "Timestamp Converter",
    description: "Двусторонняя конвертация Unix timestamp и даты во все основные форматы",
    icon: "clock",
    route: "/tools/timestamp-converter",
    backendEndpoint: null,
    savesToHistory: false,
  },
  {
    key: "utm_builder",
    section: "utility",
    order: 5,
    title: "UTM Builder",
    description: "Сборка ссылки с UTM-метками для рекламных интеграций и кросспостинга",
    icon: "route",
    route: "/tools/utm-builder",
    backendEndpoint: null,
    savesToHistory: true,
  },
  {
    key: "url_shortener",
    section: "utility",
    order: 6,
    title: "URL Shortener",
    description: "Короткая ссылка вместо длинного URL с UTM-метками, со счётчиком переходов",
    icon: "scissors",
    route: "/tools/url-shortener",
    backendEndpoint: "POST /api/tools/url-shortener",
    savesToHistory: true,
  },
  {
    key: "post_constructor",
    section: "content",
    order: 1,
    title: "Конструктор постов",
    description: "Пост по структуре хук → тело → CTA, тезисы раскладываются по секциям автоматически",
    icon: "layout-template",
    route: "/tools/post-constructor",
    backendEndpoint: "POST /api/tools/post-constructor",
    savesToHistory: true,
  },
  {
    key: "welcome_message",
    section: "content",
    order: 2,
    title: "Приветственное сообщение",
    description: "Текст приветствия для новых участников канала или группы, с плейсхолдером {name}",
    icon: "door-open",
    route: "/tools/welcome-message",
    backendEndpoint: "POST /api/tools/welcome-message",
    savesToHistory: true,
  },
  {
    key: "group_rules",
    section: "content",
    order: 3,
    title: "Правила группы",
    description: "Нумерованный список правил из типовых пунктов и своих формулировок",
    icon: "list-checks",
    route: "/tools/group-rules",
    backendEndpoint: "POST /api/tools/group-rules",
    savesToHistory: true,
  },
  {
    key: "headline_generator",
    section: "content",
    order: 4,
    title: "Генератор заголовков",
    description: "3/5/10 вариантов заголовков на тему по разным паттернам: вопрос, число, интрига и др.",
    icon: "heading",
    route: "/tools/headline-generator",
    backendEndpoint: "GET /api/tools/headline-generator",
    savesToHistory: true,
  },
  {
    key: "cta_generator",
    section: "content",
    order: 5,
    title: "Генератор CTA",
    description: "3 варианта призыва к действию под цель и тон — используется и отдельно, и внутри Конструктора постов",
    icon: "megaphone",
    route: "/tools/cta-generator",
    backendEndpoint: "POST /api/tools/cta-generator",
    savesToHistory: true,
  },
  {
    key: "hashtag_generator",
    section: "content",
    order: 6,
    title: "Генератор хештегов",
    description: "5/10/15 хештегов по теме и категории, без дублей, единый регистр",
    icon: "hash",
    route: "/tools/hashtag-generator",
    backendEndpoint: "GET /api/tools/hashtag-generator",
    savesToHistory: false,
  },
  {
    key: "banner_creator",
    section: "design",
    order: 1,
    title: "Banner Creator",
    description: "Баннер для обложки канала, поста или сторис — фон, текст, лого из Brand Kit",
    icon: "image",
    route: "/tools/banner-creator",
    backendEndpoint: "POST /api/tools/design-upload",
    savesToHistory: true,
  },
  {
    key: "avatar_creator",
    section: "design",
    order: 2,
    title: "Avatar Creator",
    description: "Аватар из фото или инициалов на цветном фоне, обрезка в круг/квадрат",
    icon: "circle-user-round",
    route: "/tools/avatar-creator",
    backendEndpoint: "POST /api/tools/design-upload",
    savesToHistory: true,
  },
  {
    key: "qr_creator",
    section: "design",
    order: 3,
    title: "QR Creator",
    description: "Фирменный QR-код на канал, группу, бота или произвольную ссылку, с лого по центру",
    icon: "qr-code",
    route: "/tools/qr-creator",
    backendEndpoint: "POST /api/tools/design-upload",
    savesToHistory: true,
  },
  {
    key: "image_resize_crop_compress",
    section: "design",
    order: 4,
    title: "Resize / Crop / Compress",
    description: "Подогнать картинку под нужный формат и вес без внешних сервисов",
    icon: "crop",
    route: "/tools/image-tools",
    backendEndpoint: "POST /api/tools/design-upload",
    savesToHistory: false,
  },
  {
    key: "color_palette_generator",
    section: "design",
    order: 5,
    title: "Color Palette Generator",
    description: "5 гармоничных цветов от базового оттенка или из загруженной картинки",
    icon: "palette",
    route: "/tools/color-palette",
    backendEndpoint: "PUT /api/projects/{project_id}/brand-kit",
    savesToHistory: false,
  },
  {
    key: "watermark_creator",
    section: "design",
    order: 6,
    title: "Watermark Creator",
    description: "Водяной знак (текст или лого) поверх изображения перед публикацией",
    icon: "stamp",
    route: "/tools/watermark-creator",
    backendEndpoint: "POST /api/tools/design-upload",
    savesToHistory: false,
  },
  {
    key: "content_plan",
    section: "growth",
    order: 1,
    title: "Контент-план",
    description: "Канбан-доска «Идея → В работе → Готово → Опубликовано» для планирования публикаций",
    icon: "kanban",
    route: "/tools/content-plan",
    backendEndpoint: "CRUD /api/projects/{project_id}/content-plan",
    savesToHistory: false,
  },
  {
    key: "content_calendar",
    section: "growth",
    order: 2,
    title: "Календарь публикаций",
    description: "Тот же контент-план по датам — месячный вид, клик по карточке открывает редактирование",
    icon: "calendar-days",
    route: "/tools/content-calendar",
    backendEndpoint: "CRUD /api/projects/{project_id}/content-plan",
    savesToHistory: false,
  },
  {
    key: "idea_generator",
    section: "growth",
    order: 3,
    title: "Генератор идей постов",
    description: "5/10 идей по нише из банка паттернов: сторителлинг, кейс, вопрос аудитории и другие",
    icon: "lightbulb",
    route: "/tools/idea-generator",
    backendEndpoint: "GET /api/tools/idea-generator",
    savesToHistory: false,
  },
  {
    key: "poll_quiz_generator",
    section: "growth",
    order: 4,
    title: "Генератор опросов/викторин",
    description: "Опрос или викторина с превью в стиле Telegram и проверкой лимитов Bot API",
    icon: "vote",
    route: "/tools/poll-quiz-generator",
    backendEndpoint: "POST /api/tools/poll-quiz-builder",
    savesToHistory: true,
  },
];

export const SECTION_LABELS: Record<ModuleConfig["section"], { title: string; description: string }> = {
  telegram_tools: {
    title: "Telegram Tools",
    description:
      "Шесть быстрых утилит для тех, кто ведёт канал или бота: без лишних шагов, результат — сразу готовая строка для копирования.",
  },
  content: {
    title: "Контент",
    description:
      "Шесть генераторов текста для канала или группы — без AI, на шаблонах, с тоном и фирменными эмодзи из Brand Kit по умолчанию.",
  },
  utility: {
    title: "Utility",
    description:
      "Общие инструменты разработчика и маркетолога: пароли, JSON, Base64, время, UTM-метки и короткие ссылки.",
  },
  design: {
    title: "Дизайн",
    description:
      "Шесть canvas-редакторов для оформления канала: баннеры, аватар, QR, обработка изображений, палитра и водяной знак — с Brand Kit по умолчанию.",
  },
  growth: {
    title: "Рост",
    description:
      "Планирование публикаций и идеи для контента: канбан и календарь на общих данных, генератор идей постов и генератор опросов/викторин.",
  },
};
